name: go-release
env:
  APPVERSION: v1.1.${{ github.run_number }}
on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: set GOPRIVATE
        run: |
          go env -w GOPRIVATE=github.com/ohdat
          git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
  release:
    # if master branch or workflow_dispatch
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.APPVERSION  }}
          target_commitish: ${{ github.sha }}